package com.hualala.supplychain.mysqltotidb.bean;

import java.math.BigDecimal;
import java.util.Date;

public class TblChainBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long billid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.groupID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.demandType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte demandtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.demandID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long demandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.orgCode
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String orgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.demandName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String demandname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String billno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.shopMallBillNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String shopmallbillno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.shopMallSupplierID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long shopmallsupplierid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.serialNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long serialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte billtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billCategory
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Integer billcategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte billstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billAddSubStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte billaddsubstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long billdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.hopeCheckDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long hopecheckdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billExecuteDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long billexecutedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billCreateBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String billcreateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billCreateTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long billcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.supplierIDs
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String supplierids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.shopIDs
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String shopids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.auditBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String auditby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.auditTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long audittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.agentRules
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte agentrules;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.auditStep
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String auditstep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.billRemark
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String billremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.reason
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.supplierID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long supplierid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.supplierName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String suppliername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.supplierLinkMan
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String supplierlinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.supplierLinkTel
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String supplierlinktel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.houseID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String houseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.houseName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String housename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.allotID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long allotid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.allotName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String allotname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.allotType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte allottype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.totalPrice
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.sourceTemplate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String sourcetemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.mainBillID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long mainbillid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.deliveryAuditBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String deliveryauditby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.deliveryAuditTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long deliveryaudittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.deliveryAuditStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte deliveryauditstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.importStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte importstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.isFrozen
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte isfrozen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.deliveryName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String deliveryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.imagePath
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String imagepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.deliveryMobile
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String deliverymobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.payRefundKey
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String payrefundkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.settleState
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte settlestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.paymentState
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Integer paymentstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.paymentWay
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String paymentway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.purchasePayAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private BigDecimal purchasepayamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.supplyKey
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String supplykey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.purchaseSupplierType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte purchasesuppliertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.purchaseInspectionDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long purchaseinspectiondate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.purchaseDeliveryDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long purchasedeliverydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.deliveryCostAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private BigDecimal deliverycostamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.isChangedDeliveryCost
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte ischangeddeliverycost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.action
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.actionTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long actiontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.createTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.actionStamp
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Date actionstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.isSendEmail
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte issendemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.imageUrl
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.isChecked
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Byte ischecked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.shopMallBillID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long shopmallbillid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.shopMallShipperID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long shopmallshipperid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.shopMallShipper
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String shopmallshipper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.mainBillNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String mainbillno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.voucherNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String voucherno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.printNum
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long printnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.actionBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String actionby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.salesmanName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private String salesmanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.salesmanID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private Long salesmanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_chain_bill.discountAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    private BigDecimal discountamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billID
     *
     * @return the value of tbl_chain_bill.billID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billID
     *
     * @param billid the value for tbl_chain_bill.billID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBillid(Long billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.groupID
     *
     * @return the value of tbl_chain_bill.groupID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.groupID
     *
     * @param groupid the value for tbl_chain_bill.groupID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.demandType
     *
     * @return the value of tbl_chain_bill.demandType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getDemandtype() {
        return demandtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.demandType
     *
     * @param demandtype the value for tbl_chain_bill.demandType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDemandtype(Byte demandtype) {
        this.demandtype = demandtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.demandID
     *
     * @return the value of tbl_chain_bill.demandID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getDemandid() {
        return demandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.demandID
     *
     * @param demandid the value for tbl_chain_bill.demandID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDemandid(Long demandid) {
        this.demandid = demandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.orgCode
     *
     * @return the value of tbl_chain_bill.orgCode
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.orgCode
     *
     * @param orgcode the value for tbl_chain_bill.orgCode
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.demandName
     *
     * @return the value of tbl_chain_bill.demandName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getDemandname() {
        return demandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.demandName
     *
     * @param demandname the value for tbl_chain_bill.demandName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDemandname(String demandname) {
        this.demandname = demandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billNo
     *
     * @return the value of tbl_chain_bill.billNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billNo
     *
     * @param billno the value for tbl_chain_bill.billNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBillno(String billno) {
        this.billno = billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.shopMallBillNo
     *
     * @return the value of tbl_chain_bill.shopMallBillNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getShopmallbillno() {
        return shopmallbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.shopMallBillNo
     *
     * @param shopmallbillno the value for tbl_chain_bill.shopMallBillNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setShopmallbillno(String shopmallbillno) {
        this.shopmallbillno = shopmallbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.shopMallSupplierID
     *
     * @return the value of tbl_chain_bill.shopMallSupplierID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getShopmallsupplierid() {
        return shopmallsupplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.shopMallSupplierID
     *
     * @param shopmallsupplierid the value for tbl_chain_bill.shopMallSupplierID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setShopmallsupplierid(Long shopmallsupplierid) {
        this.shopmallsupplierid = shopmallsupplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.serialNo
     *
     * @return the value of tbl_chain_bill.serialNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.serialNo
     *
     * @param serialno the value for tbl_chain_bill.serialNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSerialno(Long serialno) {
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billType
     *
     * @return the value of tbl_chain_bill.billType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getBilltype() {
        return billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billType
     *
     * @param billtype the value for tbl_chain_bill.billType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBilltype(Byte billtype) {
        this.billtype = billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billCategory
     *
     * @return the value of tbl_chain_bill.billCategory
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Integer getBillcategory() {
        return billcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billCategory
     *
     * @param billcategory the value for tbl_chain_bill.billCategory
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBillcategory(Integer billcategory) {
        this.billcategory = billcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billStatus
     *
     * @return the value of tbl_chain_bill.billStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getBillstatus() {
        return billstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billStatus
     *
     * @param billstatus the value for tbl_chain_bill.billStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBillstatus(Byte billstatus) {
        this.billstatus = billstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billAddSubStatus
     *
     * @return the value of tbl_chain_bill.billAddSubStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getBilladdsubstatus() {
        return billaddsubstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billAddSubStatus
     *
     * @param billaddsubstatus the value for tbl_chain_bill.billAddSubStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBilladdsubstatus(Byte billaddsubstatus) {
        this.billaddsubstatus = billaddsubstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billDate
     *
     * @return the value of tbl_chain_bill.billDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billDate
     *
     * @param billdate the value for tbl_chain_bill.billDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBilldate(Long billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.hopeCheckDate
     *
     * @return the value of tbl_chain_bill.hopeCheckDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getHopecheckdate() {
        return hopecheckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.hopeCheckDate
     *
     * @param hopecheckdate the value for tbl_chain_bill.hopeCheckDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setHopecheckdate(Long hopecheckdate) {
        this.hopecheckdate = hopecheckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billExecuteDate
     *
     * @return the value of tbl_chain_bill.billExecuteDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getBillexecutedate() {
        return billexecutedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billExecuteDate
     *
     * @param billexecutedate the value for tbl_chain_bill.billExecuteDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBillexecutedate(Long billexecutedate) {
        this.billexecutedate = billexecutedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billCreateBy
     *
     * @return the value of tbl_chain_bill.billCreateBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getBillcreateby() {
        return billcreateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billCreateBy
     *
     * @param billcreateby the value for tbl_chain_bill.billCreateBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBillcreateby(String billcreateby) {
        this.billcreateby = billcreateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billCreateTime
     *
     * @return the value of tbl_chain_bill.billCreateTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getBillcreatetime() {
        return billcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billCreateTime
     *
     * @param billcreatetime the value for tbl_chain_bill.billCreateTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBillcreatetime(Long billcreatetime) {
        this.billcreatetime = billcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.supplierIDs
     *
     * @return the value of tbl_chain_bill.supplierIDs
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getSupplierids() {
        return supplierids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.supplierIDs
     *
     * @param supplierids the value for tbl_chain_bill.supplierIDs
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSupplierids(String supplierids) {
        this.supplierids = supplierids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.shopIDs
     *
     * @return the value of tbl_chain_bill.shopIDs
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getShopids() {
        return shopids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.shopIDs
     *
     * @param shopids the value for tbl_chain_bill.shopIDs
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setShopids(String shopids) {
        this.shopids = shopids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.auditBy
     *
     * @return the value of tbl_chain_bill.auditBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getAuditby() {
        return auditby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.auditBy
     *
     * @param auditby the value for tbl_chain_bill.auditBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setAuditby(String auditby) {
        this.auditby = auditby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.auditTime
     *
     * @return the value of tbl_chain_bill.auditTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.auditTime
     *
     * @param audittime the value for tbl_chain_bill.auditTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setAudittime(Long audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.agentRules
     *
     * @return the value of tbl_chain_bill.agentRules
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getAgentrules() {
        return agentrules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.agentRules
     *
     * @param agentrules the value for tbl_chain_bill.agentRules
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setAgentrules(Byte agentrules) {
        this.agentrules = agentrules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.auditStep
     *
     * @return the value of tbl_chain_bill.auditStep
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getAuditstep() {
        return auditstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.auditStep
     *
     * @param auditstep the value for tbl_chain_bill.auditStep
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setAuditstep(String auditstep) {
        this.auditstep = auditstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.billRemark
     *
     * @return the value of tbl_chain_bill.billRemark
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getBillremark() {
        return billremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.billRemark
     *
     * @param billremark the value for tbl_chain_bill.billRemark
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setBillremark(String billremark) {
        this.billremark = billremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.reason
     *
     * @return the value of tbl_chain_bill.reason
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.reason
     *
     * @param reason the value for tbl_chain_bill.reason
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.supplierID
     *
     * @return the value of tbl_chain_bill.supplierID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.supplierID
     *
     * @param supplierid the value for tbl_chain_bill.supplierID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSupplierid(Long supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.supplierName
     *
     * @return the value of tbl_chain_bill.supplierName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getSuppliername() {
        return suppliername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.supplierName
     *
     * @param suppliername the value for tbl_chain_bill.supplierName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.supplierLinkMan
     *
     * @return the value of tbl_chain_bill.supplierLinkMan
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getSupplierlinkman() {
        return supplierlinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.supplierLinkMan
     *
     * @param supplierlinkman the value for tbl_chain_bill.supplierLinkMan
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSupplierlinkman(String supplierlinkman) {
        this.supplierlinkman = supplierlinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.supplierLinkTel
     *
     * @return the value of tbl_chain_bill.supplierLinkTel
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getSupplierlinktel() {
        return supplierlinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.supplierLinkTel
     *
     * @param supplierlinktel the value for tbl_chain_bill.supplierLinkTel
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSupplierlinktel(String supplierlinktel) {
        this.supplierlinktel = supplierlinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.houseID
     *
     * @return the value of tbl_chain_bill.houseID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getHouseid() {
        return houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.houseID
     *
     * @param houseid the value for tbl_chain_bill.houseID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setHouseid(String houseid) {
        this.houseid = houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.houseName
     *
     * @return the value of tbl_chain_bill.houseName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getHousename() {
        return housename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.houseName
     *
     * @param housename the value for tbl_chain_bill.houseName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setHousename(String housename) {
        this.housename = housename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.allotID
     *
     * @return the value of tbl_chain_bill.allotID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getAllotid() {
        return allotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.allotID
     *
     * @param allotid the value for tbl_chain_bill.allotID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setAllotid(Long allotid) {
        this.allotid = allotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.allotName
     *
     * @return the value of tbl_chain_bill.allotName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getAllotname() {
        return allotname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.allotName
     *
     * @param allotname the value for tbl_chain_bill.allotName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setAllotname(String allotname) {
        this.allotname = allotname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.allotType
     *
     * @return the value of tbl_chain_bill.allotType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getAllottype() {
        return allottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.allotType
     *
     * @param allottype the value for tbl_chain_bill.allotType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setAllottype(Byte allottype) {
        this.allottype = allottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.totalPrice
     *
     * @return the value of tbl_chain_bill.totalPrice
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.totalPrice
     *
     * @param totalprice the value for tbl_chain_bill.totalPrice
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.sourceTemplate
     *
     * @return the value of tbl_chain_bill.sourceTemplate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getSourcetemplate() {
        return sourcetemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.sourceTemplate
     *
     * @param sourcetemplate the value for tbl_chain_bill.sourceTemplate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSourcetemplate(String sourcetemplate) {
        this.sourcetemplate = sourcetemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.mainBillID
     *
     * @return the value of tbl_chain_bill.mainBillID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getMainbillid() {
        return mainbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.mainBillID
     *
     * @param mainbillid the value for tbl_chain_bill.mainBillID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setMainbillid(Long mainbillid) {
        this.mainbillid = mainbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.deliveryAuditBy
     *
     * @return the value of tbl_chain_bill.deliveryAuditBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getDeliveryauditby() {
        return deliveryauditby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.deliveryAuditBy
     *
     * @param deliveryauditby the value for tbl_chain_bill.deliveryAuditBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDeliveryauditby(String deliveryauditby) {
        this.deliveryauditby = deliveryauditby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.deliveryAuditTime
     *
     * @return the value of tbl_chain_bill.deliveryAuditTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getDeliveryaudittime() {
        return deliveryaudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.deliveryAuditTime
     *
     * @param deliveryaudittime the value for tbl_chain_bill.deliveryAuditTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDeliveryaudittime(Long deliveryaudittime) {
        this.deliveryaudittime = deliveryaudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.deliveryAuditStatus
     *
     * @return the value of tbl_chain_bill.deliveryAuditStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getDeliveryauditstatus() {
        return deliveryauditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.deliveryAuditStatus
     *
     * @param deliveryauditstatus the value for tbl_chain_bill.deliveryAuditStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDeliveryauditstatus(Byte deliveryauditstatus) {
        this.deliveryauditstatus = deliveryauditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.importStatus
     *
     * @return the value of tbl_chain_bill.importStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getImportstatus() {
        return importstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.importStatus
     *
     * @param importstatus the value for tbl_chain_bill.importStatus
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setImportstatus(Byte importstatus) {
        this.importstatus = importstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.isFrozen
     *
     * @return the value of tbl_chain_bill.isFrozen
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getIsfrozen() {
        return isfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.isFrozen
     *
     * @param isfrozen the value for tbl_chain_bill.isFrozen
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setIsfrozen(Byte isfrozen) {
        this.isfrozen = isfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.deliveryName
     *
     * @return the value of tbl_chain_bill.deliveryName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getDeliveryname() {
        return deliveryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.deliveryName
     *
     * @param deliveryname the value for tbl_chain_bill.deliveryName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDeliveryname(String deliveryname) {
        this.deliveryname = deliveryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.imagePath
     *
     * @return the value of tbl_chain_bill.imagePath
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.imagePath
     *
     * @param imagepath the value for tbl_chain_bill.imagePath
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.deliveryMobile
     *
     * @return the value of tbl_chain_bill.deliveryMobile
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getDeliverymobile() {
        return deliverymobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.deliveryMobile
     *
     * @param deliverymobile the value for tbl_chain_bill.deliveryMobile
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDeliverymobile(String deliverymobile) {
        this.deliverymobile = deliverymobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.payRefundKey
     *
     * @return the value of tbl_chain_bill.payRefundKey
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getPayrefundkey() {
        return payrefundkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.payRefundKey
     *
     * @param payrefundkey the value for tbl_chain_bill.payRefundKey
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setPayrefundkey(String payrefundkey) {
        this.payrefundkey = payrefundkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.settleState
     *
     * @return the value of tbl_chain_bill.settleState
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getSettlestate() {
        return settlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.settleState
     *
     * @param settlestate the value for tbl_chain_bill.settleState
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSettlestate(Byte settlestate) {
        this.settlestate = settlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.paymentState
     *
     * @return the value of tbl_chain_bill.paymentState
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Integer getPaymentstate() {
        return paymentstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.paymentState
     *
     * @param paymentstate the value for tbl_chain_bill.paymentState
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setPaymentstate(Integer paymentstate) {
        this.paymentstate = paymentstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.paymentWay
     *
     * @return the value of tbl_chain_bill.paymentWay
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getPaymentway() {
        return paymentway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.paymentWay
     *
     * @param paymentway the value for tbl_chain_bill.paymentWay
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setPaymentway(String paymentway) {
        this.paymentway = paymentway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.purchasePayAmount
     *
     * @return the value of tbl_chain_bill.purchasePayAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public BigDecimal getPurchasepayamount() {
        return purchasepayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.purchasePayAmount
     *
     * @param purchasepayamount the value for tbl_chain_bill.purchasePayAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setPurchasepayamount(BigDecimal purchasepayamount) {
        this.purchasepayamount = purchasepayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.supplyKey
     *
     * @return the value of tbl_chain_bill.supplyKey
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getSupplykey() {
        return supplykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.supplyKey
     *
     * @param supplykey the value for tbl_chain_bill.supplyKey
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSupplykey(String supplykey) {
        this.supplykey = supplykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.purchaseSupplierType
     *
     * @return the value of tbl_chain_bill.purchaseSupplierType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getPurchasesuppliertype() {
        return purchasesuppliertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.purchaseSupplierType
     *
     * @param purchasesuppliertype the value for tbl_chain_bill.purchaseSupplierType
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setPurchasesuppliertype(Byte purchasesuppliertype) {
        this.purchasesuppliertype = purchasesuppliertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.purchaseInspectionDate
     *
     * @return the value of tbl_chain_bill.purchaseInspectionDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getPurchaseinspectiondate() {
        return purchaseinspectiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.purchaseInspectionDate
     *
     * @param purchaseinspectiondate the value for tbl_chain_bill.purchaseInspectionDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setPurchaseinspectiondate(Long purchaseinspectiondate) {
        this.purchaseinspectiondate = purchaseinspectiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.purchaseDeliveryDate
     *
     * @return the value of tbl_chain_bill.purchaseDeliveryDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getPurchasedeliverydate() {
        return purchasedeliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.purchaseDeliveryDate
     *
     * @param purchasedeliverydate the value for tbl_chain_bill.purchaseDeliveryDate
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setPurchasedeliverydate(Long purchasedeliverydate) {
        this.purchasedeliverydate = purchasedeliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.deliveryCostAmount
     *
     * @return the value of tbl_chain_bill.deliveryCostAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public BigDecimal getDeliverycostamount() {
        return deliverycostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.deliveryCostAmount
     *
     * @param deliverycostamount the value for tbl_chain_bill.deliveryCostAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDeliverycostamount(BigDecimal deliverycostamount) {
        this.deliverycostamount = deliverycostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.isChangedDeliveryCost
     *
     * @return the value of tbl_chain_bill.isChangedDeliveryCost
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getIschangeddeliverycost() {
        return ischangeddeliverycost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.isChangedDeliveryCost
     *
     * @param ischangeddeliverycost the value for tbl_chain_bill.isChangedDeliveryCost
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setIschangeddeliverycost(Byte ischangeddeliverycost) {
        this.ischangeddeliverycost = ischangeddeliverycost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.action
     *
     * @return the value of tbl_chain_bill.action
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.action
     *
     * @param action the value for tbl_chain_bill.action
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setAction(Byte action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.actionTime
     *
     * @return the value of tbl_chain_bill.actionTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getActiontime() {
        return actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.actionTime
     *
     * @param actiontime the value for tbl_chain_bill.actionTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setActiontime(Long actiontime) {
        this.actiontime = actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.createTime
     *
     * @return the value of tbl_chain_bill.createTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.createTime
     *
     * @param createtime the value for tbl_chain_bill.createTime
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.actionStamp
     *
     * @return the value of tbl_chain_bill.actionStamp
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Date getActionstamp() {
        return actionstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.actionStamp
     *
     * @param actionstamp the value for tbl_chain_bill.actionStamp
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setActionstamp(Date actionstamp) {
        this.actionstamp = actionstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.isSendEmail
     *
     * @return the value of tbl_chain_bill.isSendEmail
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getIssendemail() {
        return issendemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.isSendEmail
     *
     * @param issendemail the value for tbl_chain_bill.isSendEmail
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setIssendemail(Byte issendemail) {
        this.issendemail = issendemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.imageUrl
     *
     * @return the value of tbl_chain_bill.imageUrl
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.imageUrl
     *
     * @param imageurl the value for tbl_chain_bill.imageUrl
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.isChecked
     *
     * @return the value of tbl_chain_bill.isChecked
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Byte getIschecked() {
        return ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.isChecked
     *
     * @param ischecked the value for tbl_chain_bill.isChecked
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setIschecked(Byte ischecked) {
        this.ischecked = ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.shopMallBillID
     *
     * @return the value of tbl_chain_bill.shopMallBillID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getShopmallbillid() {
        return shopmallbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.shopMallBillID
     *
     * @param shopmallbillid the value for tbl_chain_bill.shopMallBillID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setShopmallbillid(Long shopmallbillid) {
        this.shopmallbillid = shopmallbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.shopMallShipperID
     *
     * @return the value of tbl_chain_bill.shopMallShipperID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getShopmallshipperid() {
        return shopmallshipperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.shopMallShipperID
     *
     * @param shopmallshipperid the value for tbl_chain_bill.shopMallShipperID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setShopmallshipperid(Long shopmallshipperid) {
        this.shopmallshipperid = shopmallshipperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.shopMallShipper
     *
     * @return the value of tbl_chain_bill.shopMallShipper
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getShopmallshipper() {
        return shopmallshipper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.shopMallShipper
     *
     * @param shopmallshipper the value for tbl_chain_bill.shopMallShipper
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setShopmallshipper(String shopmallshipper) {
        this.shopmallshipper = shopmallshipper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.mainBillNo
     *
     * @return the value of tbl_chain_bill.mainBillNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getMainbillno() {
        return mainbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.mainBillNo
     *
     * @param mainbillno the value for tbl_chain_bill.mainBillNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setMainbillno(String mainbillno) {
        this.mainbillno = mainbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.voucherNo
     *
     * @return the value of tbl_chain_bill.voucherNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getVoucherno() {
        return voucherno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.voucherNo
     *
     * @param voucherno the value for tbl_chain_bill.voucherNo
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setVoucherno(String voucherno) {
        this.voucherno = voucherno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.printNum
     *
     * @return the value of tbl_chain_bill.printNum
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getPrintnum() {
        return printnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.printNum
     *
     * @param printnum the value for tbl_chain_bill.printNum
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setPrintnum(Long printnum) {
        this.printnum = printnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.actionBy
     *
     * @return the value of tbl_chain_bill.actionBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getActionby() {
        return actionby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.actionBy
     *
     * @param actionby the value for tbl_chain_bill.actionBy
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setActionby(String actionby) {
        this.actionby = actionby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.salesmanName
     *
     * @return the value of tbl_chain_bill.salesmanName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public String getSalesmanname() {
        return salesmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.salesmanName
     *
     * @param salesmanname the value for tbl_chain_bill.salesmanName
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSalesmanname(String salesmanname) {
        this.salesmanname = salesmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.salesmanID
     *
     * @return the value of tbl_chain_bill.salesmanID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public Long getSalesmanid() {
        return salesmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.salesmanID
     *
     * @param salesmanid the value for tbl_chain_bill.salesmanID
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setSalesmanid(Long salesmanid) {
        this.salesmanid = salesmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_chain_bill.discountAmount
     *
     * @return the value of tbl_chain_bill.discountAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public BigDecimal getDiscountamount() {
        return discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_chain_bill.discountAmount
     *
     * @param discountamount the value for tbl_chain_bill.discountAmount
     *
     * @mbg.generated Mon Feb 24 12:27:00 CST 2020
     */
    public void setDiscountamount(BigDecimal discountamount) {
        this.discountamount = discountamount;
    }
}